#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ Vérification du formatage et du linting...'

npx lint-staged || {
    echo '❌ Erreur de formatage ou de linting détectée'
    exit 1
}

echo '✅ Code vérifié avec succès!'